Add ticket 5 for review
TKeyes267/NC-news pull request #5
Opened 2023-03-28 15:04 UTC by TKeyes267

2023-03-28 15:12 UTC, NRMSMITH requested changes

2023-03-28 15:12 UTC, NRMSMITH commented on __tests__/app.test.js
> +describe.only("GET /api/articles", () => {
get rrid of this only please and then I will review :D

2023-03-28 15:21 UTC, NRMSMITH requested changes
implement jest-sorted for readability and then send another pr tomorrow please :)

2023-03-28 15:21 UTC, NRMSMITH commented on app.js
>  app.use(express.json());
❌ You're not patching/posting so you don't need this yet

2023-03-28 15:21 UTC, NRMSMITH commented on __tests__/app.test.js
> +      });
You'd be better off having a look at jest-sorted than checking the specific dates.

2023-03-29 08:18 UTC, itskatherine reviewed
Hi Tom, nice work - missing a test (though I'd believe you'd pass it if you added it in)
Have a look over my comments and once you've addressed them, you're good to merge 👍

2023-03-29 08:18 UTC, itskatherine commented on __tests__/app.test.js
> +            comment_count: expect.any(String),
I would expect comment_count to be a number rather than a string - have a look into [SQL casting](https://www.w3schools.com/sql/func_sqlserver_cast.asp) to see how you can achieve this in your query

2023-03-29 08:52 UTC, merged